In [79]:
import pandas as pd
import numpy as np
df = pd.read_csv('고령자 데이터 합 20221220.csv', encoding='cp949')
df = df.set_index('Unnamed: 0', drop=True)

In [80]:
new_df = df.iloc[12:-1]
new_df['코로나 확진자 수'] = new_df['코로나 확진자 수'].fillna(0)
new_df

C:\Users\user\AppData\Local\Temp\ipykernel_11380\60118038.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['코로나 확진자 수'] = new_df['코로나 확진자 수'].fillna(0)

,65세 이상 경제활동인구 (천 명),65세 이상 경제활동참가율 (%),65세 이상 고용률 (%),65세 이상 비경제활동인구 (천 명),65세 인구 (천 명),취업자 수 (천 명),총인구 수,서울 주유비 (원),65세 이상 질병 사망자 수,65세 이상 자진반납 현황,경제성장률 (%),코로나 확진자 수,65세 이상 사망자 수
Unnamed: 0,,,,,,,,,,,,,
2011,238.0,24.5,23.6,732.0,970.0,229.0,"10,249,679",1995.59,156.0,NaN,3.7,0.0,23762.0
2012,263.0,25.6,24.7,765.0,1028.0,254.0,"10,195,318",2058.96,154.0,NaN,2.4,0.0,24983.0
2013,276.0,25.4,24.8,813.0,1089.0,271.0,"10,143,645",2002.96,179.0,NaN,3.2,0.0,25345.0
2014,318.0,27.7,27.0,831.0,1149.0,310.0,"10,103,233",1914.95,193.0,NaN,3.2,0.0,25598.0
2015,322.0,26.7,25.9,883.0,1205.0,313.0,"10,022,181",1596.74,220.0,348.0,2.8,0.0,26509.0
2016,326.0,26.3,25.7,915.0,1241.0,319.0,"9,930,616",1499.82,196.0,447.0,2.9,0.0,26885.0
2017,345.0,26.7,25.7,947.0,1292.0,332.0,"9,857,426",1589.52,264.0,799.0,3.2,0.0,26642.0
2018,356.0,26.5,25.4,990.0,1346.0,343.0,"9,765,623",1670.03,307.0,1387.0,2.9,0.0,28473.0
2019,410.0,29.3,28.0,990.0,1400.0,393.0,"9,729,107",1567.52,360.0,17393.0,2.2,0.0,27491.0
2020,433.0,29.3,27.8,1046.0,1479.0,412.0,"9,668,465",1470.37,382.0,14296.0,-0.7,60726.0,28786.0
2021,434.0,27.9,26.0,1121.0,1555.0,411.0,"9,509,458",1668.46,408.0,15391.0,4.1,570057.0,31218.0

In [81]:
new_df['총인구 수'] = new_df['총인구 수'].str.replace(',','').astype('int64')
for i in range(0, 9):
    new_df.iloc[:,i] = new_df.iloc[:,i].astype('int64')
    
new_df['경제성장률 (%)'] = new_df['경제성장률 (%)'].astype('int64')
new_df['코로나 확진자 수'] = new_df['코로나 확진자 수'].astype('int64')
new_df['65세 이상 사망자 수'] = new_df['65세 이상 사망자 수'].astype('int64')

C:\Users\user\AppData\Local\Temp\ipykernel_11380\3610184464.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['총인구 수'] = new_df['총인구 수'].str.replace(',','').astype('int64')
C:\Users\user\AppData\Local\Temp\ipykernel_11380\3610184464.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.iloc[:,i] = new_df.iloc[:,i].astype('int64')
C:\Users\user\AppData\Local\Temp\ipykernel_11380\3610184464.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['경제성장률 (%)'] = new_df['경제성장률 (%)'].astype('int64')
C:\Users\user\AppData\Local\Temp\ipykernel_11380\3610184464.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['코로나 확진자 수'] = new_df['코로나 확진자 수'].astype('int64')
C:\Users\user\AppData\Local\Temp\ipykernel_11380\3610184464.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['65세 이상 사망자 수'] = new_df['65세 이상 사망자 수'].astype('int64')

In [89]:
new_df["65세 이상 자진반납 현황"] = new_df["65세 이상 자진반납 현황"].fillna("0").astype(int)
new_df

C:\Users\user\AppData\Local\Temp\ipykernel_11380\3151899258.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["65세 이상 자진반납 현황"] = new_df["65세 이상 자진반납 현황"].fillna("0").astype(int)

,65세 이상 경제활동인구 (천 명),65세 이상 경제활동참가율 (%),65세 이상 고용률 (%),65세 이상 비경제활동인구 (천 명),65세 인구 (천 명),취업자 수 (천 명),총인구 수,서울 주유비 (원),65세 이상 질병 사망자 수,65세 이상 자진반납 현황,경제성장률 (%),코로나 확진자 수,65세 이상 사망자 수
Unnamed: 0,,,,,,,,,,,,,
2011,238,24,23,732,970,229,10249679,1995,156,0,3,0,23762
2012,263,25,24,765,1028,254,10195318,2058,154,0,2,0,24983
2013,276,25,24,813,1089,271,10143645,2002,179,0,3,0,25345
2014,318,27,27,831,1149,310,10103233,1914,193,0,3,0,25598
2015,322,26,25,883,1205,313,10022181,1596,220,348,2,0,26509
2016,326,26,25,915,1241,319,9930616,1499,196,447,2,0,26885
2017,345,26,25,947,1292,332,9857426,1589,264,799,3,0,26642
2018,356,26,25,990,1346,343,9765623,1670,307,1387,2,0,28473
2019,410,29,28,990,1400,393,9729107,1567,360,17393,2,0,27491
2020,433,29,27,1046,1479,412,9668465,1470,382,14296,0,60726,28786
2021,434,27,26,1121,1555,411,9509458,1668,408,15391,4,570057,31218

In [83]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imputer = IterativeImputer(random_state=0)
imputer.fit(df)
mm_df = imputer.transform(df)
mm_df

ValueError: could not convert string to float: '10,312,545'